title: Spotty
description: ''
baseurl: ''
url: ''

# build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed

# the theme settings
search_enabled: true
aux_links:
    GitHub:
      - https://github.com/apls777/spotty
